apiVersion: v2
name: AllureTestops
description: Helm Chart for localfirst/AllureTestops
home: https://cheddartv.github.io/helm-charts
sources:
  - https://cheddartv.github.io/helm-charts
  - https://hub.docker.com/r/allure/allure-ui
  - https://hub.docker.com/r/allure/allure-uaa
  - https://hub.docker.com/r/allure/allure-report
maintainers:
  - email: priya.bommineni@cheddar.com
    name: PriyaBommineni
type: application
version: 1.5.0
appVersion: "1.0.0"

dependencies:
  - name: rabbitmq
    version: 10.1.14
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: 17.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
