deployment:
  configmap__name: "temp"
  mains:
    name: temp
    namespace: staging
    replicas: 1
    image: ${artifact.metadata.image}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  env:
    config:
      UseMe: "false"
    secrets:
      names:
        - secrets
