{{- if .Values.deployment.autoscaling}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.deployment.main.name}}
  namespace: {{.Values.deployment.namespace}}
  labels:
{{- if .Values.deployment.main.app_labels}}
{{.Values.app_labels | toYaml | trim | indent 4 }}
{{- end}}
{{- if not .Values.deployment.main.app_labels}}
    app: {{.Values.deployment.main.name}}
{{- end}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.deployment.main.name}}
  minReplicas: {{.Values.deployment.autoscaling.minReplicas}}
  maxReplicas: {{.Values.deployment.autoscaling.maxReplicas}}
  metrics:
{{- with .Values.deployment.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ . }}
{{- end }}
{{- with .Values.deployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ . }}
{{- end }}
{{- end }}