{{- if .Values.service}}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}-svc
  namespace: {{.Values.service.namespace}}
  labels:
    app: {{.Values.service.name}}
spec:
  type: {{.Values.service.serviceType}}
  ports:
  - port: {{.Values.service.servicePort}}
    targetPort: {{.Values.service.port}}
    protocol: TCP
    name: {{ .Values.service.portname}}
  selector:
    {{- if .Values.deployment.main.name}}
    app: {{.Values.deployment.main.name}}
    {{- else}}
    app: {{.Values.service.name}}
    {{- end}}
{{- end}}
