name: Helm dry run

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - charts/DigitalAudience/**
      - .github/workflows/digitalplan-test.yml

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      - name: Clone localfirst repository
        uses: actions/checkout@v2
        with:
          repository: cheddartv/localfirst
          path: localfirst
          ref: main

      - name: Helm dry run (install)
        run: helm install digitalplan --dry-run --debug --hide-secrets -f localfirst/Digital.Plan/k8s/staging/values.yml charts/DigitalPlan
