name: Helm dry run

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - charts/**
      - .github/workflows/helm-dryrun.yaml

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      - name: Clone localfirst repository
        uses: actions/checkout@v2
        with:
          repository: cheddartv/localfirst
          token: ${{ secrets.ACCESS_TOKEN }}
          path: localfirst
          ref: main

      - name: changed-files
        uses: pankajnarang/last_commit@main

      - name: Check the output for folder name
        run: echo "${{ env.folderName }}"

      - name: Exiting workflow if changes are on github workflow
        run: |
         
          if [[ ${{ env.folderName }} == ".github" ]]
          then
               echo "No changes are made in charts"
               exit=true
          fi

      - name: Original value path if folder with multiple words
        run: |
        
          if [[ ${{ env.folderName }} == "DigitalAudience" ]]
          then
               VALUES_PATH="Digital.Audience"
          elif [[ ${{ env.folderName }} == "DigitalPlan" ]]
          then
               VALUES_PATH="Digital.Plan"
          else
               VALUES_PATH="${{ env.folderName }}"
          fi

      - name: Check the app path to original values
        run: echo "$VALUES_PATH"

      - name: Helm dry run (install)
        run: 
          if [[ exit == true ]] 
          then
               echo "No changes are on charts and ending workflow"
          else
	       helm install ${{ env.folderName }} --dry-run --debug -f localfirst/$VALUES_PATH/k8s/staging/values.yaml charts/${{ env.folderName }}
	       helm install ${{ env.folderName }} --dry-run --debug -f localfirst/$VALUES_PATH/k8s/prod/values.yaml charts/${{ env.folderName }}
          fi
